name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.104
    - name: Install dependencies
      working-directory: ./ProjectADApi/ProjectADApi
      run: dotnet restore
    - name: Build net core
      working-directory: ./ProjectADApi/ProjectADApi
      run: dotnet build --configuration Release 
    - name: Deploy net core
      run: dotnet publish src -c Release -o BlueDeploy
    
